[package]
name = "libfiber"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE.txt"

[dependencies]

[build-dependencies]
# 从c/c++头文件自动生成rust
bindgen = "0.59.2"
cc = "1.0.73"
rustversion = "1.0.6"

[dev-dependencies]
# benchmark
criterion = "0.3.5"

[[bench]]
name = "echo"
harness = false